auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: loki
  storage:
    s3:
      bucketnames: loki
      region: eu-central-1
  # storage:
  #   filesystem:
  #     chunks_directory: /tmp/loki/chunks
  #     rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

frontend:
  max_outstanding_per_tenant: 2048

# pattern_ingester:
#   enabled: true

limits_config:
  max_global_streams_per_user: 0
  ingestion_rate_mb: 50000
  ingestion_burst_size_mb: 50000
  volume_enabled: true
  max_label_names_per_series: 25

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      # object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks

# storage_config:
#   aws:
#     s3: http://admin:minioadmin@minio:9000/loki
#     s3forcepathstyle: true
#   tsdb_shipper:
#     active_index_directory: /home/loki/tsdb-index
#     cache_location: /home/loki/tsdb-cache
#     resync_interval: 5s

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false
