services:
  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=nfluxadmin
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_PANELS_ENABLE_ALPHA=true
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall lokiLogsDataplane
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/data-sources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/org.yml:/etc/grafana/provisioning/organizations/organization.yml

  loki:
    image: docker.io/grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data-chunks:/loki/chunks
      - loki-data-index:/loki/index
      - loki-data-cache:/loki/index_cache
    command: -config.file=/etc/loki/loki-config.yaml

volumes:
  loki-data-chunks:
  loki-data-index:
  loki-data-cache:
  grafana-storage:

networks:
  monitoring:
    external: false
    driver: bridge
